AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'
    - 'test/**/*'
    - 'TAGS'

# ConditionalAssignment:
#   Enabled: false
# StringLiterals:
#   Enabled: false
# RedundantReturn:
#   Enabled: false
Style/Documentation:
  Enabled: false
# WordArray:
#   Enabled: false
# AbcSize:
#   Enabled: false
# MutableConstant:
#   Enabled: false
# SignalException:
#   Enabled: false
# Casecmp:
#   Enabled: false
# CyclomaticComplexity:
#   Enabled: false
# MissingRespondToMissing:
#   Enabled: false
# MethodMissingSuper:
#   Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120
# Style/EmptyMethod:
#   Enabled: false
Bundler/OrderedGems:
  Enabled: false
